### ISSUE TITLE
column width in bp

### ISSUE THREAD

**Issue by asherbryant** [snystrom/vplot#18]
Hello, Spencer!  Thank you for creating this resource!

If your matrices are based on Henikoff, is the sum total width in bp of all of the 14 columns 400? 
Or is it 1000 as in your html example?

Best wishes,
Asher

**Comment by snystrom** [comment]
Hi, thanks for trying out the tool! 

I'm a bit confused what you mean. The width of the region supplied in your bed file determines the width of the matrix. If you provide a 400 bp region in the bed file, the matrix will be 400x1000. If you are getting a matrix that is less than the width of your region, that is a bug. Vplot doesn't do any kernel-density smoothing so each pixel should be a 1:1 mapping between genomic position and fragment size. 

If you provide an example file and the command used to run the program I can help further.

**Comment by asherbryant** [comment]
Oh! Sorry for my confusion; no bug at all!  I thought your vplots had fixed bp region.
That's great that the bp region is determined by the user!  
All the best!

**Comment by snystrom** [comment]
Awesome! Always happy to help!
